import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Triift Africa.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid h-screen place-items-center">
        <div className="font-bold text-3xl">Triift Africa.</div>
      </div>
     
    </div>
  )
}
